version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "soa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d soa" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      dev:
        ipv4_address: 172.20.0.2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  first-1:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    links:
      - postgres
    networks:
      dev:
        ipv4_address: 172.20.0.3
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  first-2:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8080"
    links:
      - postgres
    networks:
      dev:
        ipv4_address: 172.20.0.4
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  haproxy:
    image: haproxy:latest
    ports:
      - "8089:8089"
      - "8090:8090"
      - "443:443"
    networks:
      dev:
        ipv4_address: 172.20.0.5
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./key.pem:/usr/local/etc/haproxy/key.pem
    depends_on:
      - first-1
      - first-2

  consul:
    image: hashicorp/consul:latest
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      dev:
        ipv4_address: 172.20.0.6
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 30s
      timeout: 10s
      retries: 3

  registrator:
    image: gliderlabs/registrator:master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://consul:8500
    networks:
      dev:
        ipv4_address: 172.20.0.7
    depends_on:
      consul:
        condition: service_healthy

  second-1:
    build: second-service/
    ports:
      - "8082:8081"
    networks:
      dev:
        ipv4_address: 172.20.0.8
    links:
      - first-1
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=password

  second-2:
    build: second-service/
    ports:
      - "8083:8081"
    networks:
      dev:
        ipv4_address: 172.20.0.9
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=password

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16