version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "soa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d soa" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  first-1:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  first-2:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8080"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  second-1:
    build: second-service/
    ports:
      - "8082:8081"
    links:
      - first-1
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=password

  second-2:
    build: second-service/
    ports:
      - "8083:8081"
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=password