version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "soa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d soa" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      dev:
        ipv4_address: 172.20.0.2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  first-1:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    links:
      - postgres
      - consul
    networks:
      dev:
        ipv4_address: 172.20.0.3
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  first-2:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    links:
      - postgres
      - consul
    networks:
      dev:
        ipv4_address: 172.20.0.4
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  haproxy:
    image: haproxy:latest
    ports:
      - "8089:8089"
      - "8090:8090"
      - "443:443"
      - "9000:9000"
    networks:
      dev:
        ipv4_address: 172.20.0.5
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./key.pem:/usr/local/etc/haproxy/key.pem
    depends_on:
      consul:
        condition: service_started

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      dev:
        ipv4_address: 172.20.0.6
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 10s
      timeout: 10s
      retries: 3

  second-1:
    build: second-service/
    ports:
      - "9990:9990"
    networks:
      dev:
        ipv4_address: 172.20.0.8
    links:
      - haproxy

  second-2:
    build: second-service/
    ports:
      - "9991:9990"
    links:
      - haproxy
    networks:
      dev:
        ipv4_address: 172.20.0.9

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
